<?php echo $this->navigation()->menu()->renderMenu($this->navigation()->findOneByLabel('MainNavigation'), array('ulClass' => 'Navigation')); ?>
<br /><br />    
    <div>
    <?php print_r($this->test); ?><br /><br />
    <b>Start: </b>
    <input type="text" id="start" style="width: 200px;" />
    <!-- <b>Zwischenziel:</b>
    <input type="text" id="waypoint" />  -->
    <b>End: </b>
    <select id="end">
    <?php foreach($this->travelpoints as $destination): ?>
    	<option value="<?php echo $destination['t_lat']; ?>,<?php echo $destination['t_lng']; ?>">
    		<?php echo $destination['t_name']; ?>
    	</option>
    <?php endforeach; ?>
    </select>
    <br />
    <br />
	<b>Abfahrt: </b>
	<input id="datePicker" type="text" />
	&nbsp;
	<b>Uhrzeit </b>
	<select id="hours">
		<option value="00">00</option>
		<option value="01">01</option>	
		<option value="02">02</option>
		<option value="03">03</option>
		<option value="04">04</option>
		<option value="05">05</option>
		<option value="06">06</option>
		<option value="07">07</option>
		<option value="08">08</option>
		<option value="09">09</option>
		<option value="10">10</option>
		<option value="11">11</option>
		<option value="12">12</option>
		<option value="13">13</option>
		<option value="14">14</option>
		<option value="15">15</option>
		<option value="16">16</option>
		<option value="17">17</option>
		<option value="18">18</option>
		<option value="19">19</option>
		<option value="20">20</option>
		<option value="21">21</option>
		<option value="22">22</option>
		<option value="23">23</option>
	</select>
	&nbsp;
	<select id="minutes">
		<option value="00">00</option>
		<option value="05">05</option>
		<option value="10">10</option>
		<option value="15">15</option>
		<option value="20">20</option>
		<option value="25">25</option>
		<option value="30">30</option>
		<option value="35">35</option>
		<option value="40">40</option>
		<option value="45">45</option>
		<option value="50">50</option>
		<option value="55">55</option>
	</select>	
	<input id="date" type="hidden" />
    <br />
	<br />
	<b>Fahrzeug: </b>
	<select id="cars">
	<option value=""></option>
    <?php foreach($this->cars as $cars): ?>
    	<option value="<?php echo $cars['c_Seats']; ?>">
    		<?php echo $cars['c_Manufacturer']; ?> <?php echo $cars['c_Model']; ?>
    	</option>
    <?php endforeach; ?>
    </select>
	&nbsp;
	<b>freie Sitzplätze: </b><span id="seatsText"></span>
	<script>
	$("#cars").change(function () {
		var seats = "";
		$("#cars option:selected").each(function () {
            seats = $(this).val();
		});
		$("#seatsText").text(seats);
	})
	</script>
	<br />
    <br />
	<b>Toleranz Zeit: </b>
	<select id="toleranceDuration">
		<option value="0">egal</option>
		<option value="5">5 Minuten</option>
		<option value="10">10 Minuten</option>
		<option value="15">15 Minuten</option>
		<option value="20">20 Minuten</option>
	</select>
	<br />
    <br />
	<b>Toleranz Weg: </b>
	<select id="toleranceDistance">
		<option value="0">egal</option>
		<option value="10">10 km</option>
		<option value="20">20 km</option>
		<option value="30">30 km</option>
	</select>
	<br />
    <br />
    <a href="#" onclick="calcRoute();">berechenen</a>
    <br /><br />
    <a href="#" onclick="sendJson();">speichern</a>
    <br /><br />
    <span id="debug"></span>
    <p>Distanz: <span id="total"></span></p>
    </div>
    <div id="map_canvas" style="top:30px; height: 600px; width: 600px;"></div>
    <br /><br /><br />