<?php  $this->translation = Zend_Registry::get('Zend_Translate'); ?>


<div class="box red _1c2r search">
    <div class="boxHeader">Suchen<span></span></div>
    <div class="boxContent">
		<?php echo $this->requestForm ?>
    </div>
</div>
<div class="box yellow _1c2r offer">
    <div class="boxHeader">Anbieten<span></span></div>
    <div class="boxContent">
		<?php echo $this->rideForm ?>
    </div>
</div>
<div class="box blue _1c2r calendar">
    <div class="boxHeader">Kalender<span></span></div>
    <div class="boxContent">
		<a href="/de/calendar">Kalender</a>
    </div>
</div>
<div class="box grey right _1c2r account">
    <div class="boxHeader">Konto<span></span></div>
</div>
<div class="clearfix"></div>
            
	<?php if($this->user && false): ?>
		<img src="https://graph.facebook.com/<?php echo $this->userProfile['id']?>/picture"/>
		<?php echo $this->userProfile['first_name']; ?> <?php echo $this->userProfile['last_name']; ?><br />
		<?php echo $this->userProfile['gender']; ?><br />
		<?php echo (key_exists('email', $this->userProfile)) ? $this->userProfile['email'] : ""; ?><br />
		<?php echo $this->userProfile['id']; ?><br />
		<br />
		<br />
		<a href="<?php echo $this->logoutUrl; ?>">Logout</a>
		<?php //print_r($this->userProfile); ?>
		<br >
		<?php //print_r($this->userFriends); ?>
		<br /><br />
		<?php if(false): ?>
			<?php  foreach($this->userFriends['data'] as $friend): ?>
				<img src="https://graph.facebook.com/<?php echo $friend['id']?>/picture?type=square"/>
				<?php echo $friend['name']; ?><br />
				<br />
			<?php endforeach; ?>
		<?php endif; ?>
	<?php else: ?>
		<!-- <a href="<?php echo $this->loginUrl; ?>">Facebook Login</a>  -->
	<?php endif; ?>
	<?php //print_r($this->userProfile); ?>

