<?php  $this->translation = Zend_Registry::get('Zend_Translate'); ?>
<div class="Manager">
<div class="Left">
	<div class="LeftHeader">
		<?php echo $this->translation->translate("Navigation"); ?>
	</div>
	<div class="Info">
	<?php echo $this->translation->translate("Welcome"); ?>,<br />
	<?php echo $this->Fullname; ?>
	</div>
	<?php //echo $this->navigation()->menu()->renderMenu($this->navigation()->findOneByLabel('MainNavigation'), array('ulClass' => 'Navigation')); ?>
	
</div>
<div class="Right">
	<div class="RightHeader">
		<?php echo $this->translation->translate("Uniride.de"); ?>
	</div>
	<div class="Content">
	<div><?php echo $this->translation->translate("Willkommen bei der MFZ der Uni Siegen"); ?></div>
		<a href="<?php echo $this->loginUrl; ?>">Facebook Login</a>

	<div id="chart_div1" style="float:left;"></div>
	<div id="chart_div2" style="float:left;"></div>
	<div class="clearfix"></div>
	</div>
</div>
<div class="clearfix"></div>
</div>



