<?php echo $this->navigation()->menu()->renderMenu($this->navigation()->findOneByLabel('MainNavigation'), array('ulClass' => 'Navigation')); ?>

<link href="/css/fullcalendar.css" rel="stylesheet" type="text/css" />
<script src="/js/fullcalendar.js" type="text/javascript"></script>
<script src="/js/jquery.js" type="text/javascript"></script>

<script>
$(document).ready(function() {
    // page is now ready, initialize the calendar...
    $("#calendar").fullCalendar({
        // put your options and callbacks here
    })

});
</script>

<div id="calendar"></div>