<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width = 1024" /> 
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>uniride.de</title>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,600,700,300' rel='stylesheet' type='text/css'>
<link href="/css/styles.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="/js/jquery/jquery.min.js"></script>
<script type="text/javascript" src="/js/waypoints.min.js"></script>
<?php //echo $this->headScript() ?>
</head>

<body>
<div id="top" class="page">
    <header class="header">
        <div class="headerInner">
        	<a href="/" class="logo"><img src="/img/logo.png" width="163" height="40"></a>
            <div class="logoText">Die Mitfahrzentrale der Universität Siegen</div>
            <div class="userContainer">
            	<div class="userName">
            		<font class="firstname"><?php echo $this->userProfile['first_name']; ?><br /></font>
					<font class="lastname"><?php echo $this->userProfile['last_name']; ?></font>
				</div>
				<div class="userPicture">
            		<img src="https://graph.facebook.com/<?php echo $this->userProfile['id']?>/picture?width=62&height=62"/>
            	</div>
            	<div class="clearfix"></div>
            </div>
	        <div class="clearfix"></div>
        </div>
    </header>
    <section class="mainContainer">
        <div class="main">
        	<?php 
			   echo $this->layout()->content;
			?>        
        </div>
    </section>
    <footer class="footer">
        <div class="footerInner">
        	<ul class="footerNavigation">
            	<li>
                    <a href="#">uniride</a>
                    <ul>
                        <li><a href="#">Startseite</a></li>
                        <li><a href="#">Fahrt suchen</a></li>
                        <li><a href="#">Fahrt anbieten</a></li>
                        <li><a href="#">Kalender</a></li>
                        <li><a href="#">Mein Konto</a></li>
                    </ul>
            	</li>
                <li>
                    <a href="#">Hilfe</a>
                    <ul>
                        <li><a href="#">Anleitung</a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Support</a></li>
                    </ul>
            	</li>
                <li>
                    <a href="#">Über uniride</a>
                    <ul>
                        <li><a href="#">Kontakt</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Jobs</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Presse</a></li>
                        <li><a href="#">Partner</a></li>
                    </ul>
            	</li>
                <li>
                    <a href="#">Unternehmen</a>
                    <ul>
                        <li><a href="#">Ihre Vorteile</a></li>
                        <li><a href="#">uniride an Deiner Uni</a></li>
                        <li><a href="#">Unternehmen</a></li>
                        <li><a href="#">Broschüre</a></li>
                        <li><a href="#">Studie</a></li>
                    </ul>
            	</li>
                <li>
                    <a href="#">Social</a>
                    <ul>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Google+</a></li>
                    </ul>
            	</li>
                <li>
                    <a href="#">Rechtliches</a>
                    <ul>
                        <li><a href="#">Datenschutz</a></li>
                        <li><a href="#">AGB</a></li>
                        <li><a href="#">Impressum</a></li>
                    </ul>
            	</li>
                <div class="clearfix"></div>
            </ul>
        </div>
    </footer>
</div>
<script type="text/javascript" src="js/uniride.js"></script>
</body>
</html>

